/* §3 §6 — reported directly, with a 3D Studio screenshot showing a badly
   garbled cabinet front ("3d studio vender tegningen på hovedet"). Root
   cause, confirmed by inspecting the live Three.js scene: a wardrobe-
   planner frame can carry BOTH its own exterior front (f.front, generated
   once per whole frame in generateWardrobePlanner) AND, independently, its
   own interior zones' doors/drawers (generated by the shared
   generateCabinet() every column already goes through) — two complete,
   overlapping front systems occupying the same physical space.

   wardrobePlannerEnsure() gets this right ONCE, at first setup: an
   incoming 'doors' zone is converted to 'open' and the frame's own front
   is set instead. But nothing re-applies that rule afterwards — the 3D
   Studio's generic "Add → Door zone" / "Add → Drawer zone" cards
   (studioAdd) write straight into cfg.columns[].zones with no idea the
   planner has its own front concept, and recreate the double front the
   moment a doors/drawers zone is added to a frame that already has one. */
const {boot,suite}=require('./harness');
const t=suite('14-planner-double-front · a frame front and its own zone fronts never both generate geometry');
const h=boot(),{W}=h;
const mm=v=>Math.round(v*10);

const fit={W:mm(3200),H:mm(2350),D:mm(600),scribe:0,fillerW:0,wOut:0,hOut:0};

/* ── the actual failure: a frame with front:'hinged' whose interior zones
   ALSO contain their own doors/drawers (exactly what studioAdd produces) ── */
{
  const cfg={columns:[{w:1,zones:[{type:'doors',ratio:.45,count:2},{type:'open',ratio:.55,shelves:2}]}],
    wardrobePlanner:{room:{w:mm(1200),d:mm(2500),h:mm(2400)},
      frames:[{id:'f1',wall:'back',w:mm(1000),d:mm(600),h:mm(2300),front:'hinged',frontCount:2,handle:'bar',zones:null}],
      obstacles:[],frameColor:'#F4F2ED',frontColor:'#F4F2ED'}};
  cfg.wardrobePlanner.frames[0].zones=cfg.columns[0].zones;
  cfg.zones=cfg.columns[0].zones;
  const res=W.generate(cfg,fit);
  const doors=res.parts.filter(p=>p.k==='door');
  t.ok('exactly one door PART for the frame (not the interior zone\'s AND a duplicate frame-level one)',
    doors.length===1, doors.length+' door parts: '+JSON.stringify(doors.map(d=>({zi:d.zi,plannerFront:!!d.plannerFront,q:d.q}))));
  t.ok('the surviving door is the interior zone\'s own (has a zi), not the frame-wide duplicate',
    doors[0].zi===0&&!doors[0].plannerFront);
  t.ok('the interior open zone\'s shelves are also present (nothing else got dropped)',
    res.parts.some(p=>p.k==='shelf'));
}

/* ── a frame with a doors zone AND a drawers zone, both must survive
   without a duplicate frame-level front on top ── */
{
  const cfg={columns:[{w:1,zones:[{type:'doors',ratio:.5,count:2},{type:'drawers',ratio:.5,count:3}]}],
    wardrobePlanner:{room:{w:mm(1200),d:mm(2500),h:mm(2400)},
      frames:[{id:'f1',wall:'back',w:mm(1000),d:mm(600),h:mm(2300),front:'sliding',frontCount:2,handle:'bar',zones:null}],
      obstacles:[],frameColor:'#F4F2ED',frontColor:'#F4F2ED'}};
  cfg.wardrobePlanner.frames[0].zones=cfg.columns[0].zones;
  cfg.zones=cfg.columns[0].zones;
  const res=W.generate(cfg,fit);
  t.ok('exactly one door part and one drawerfront part, no frame-level duplicate front',
    res.parts.filter(p=>p.k==='door').length===1 && res.parts.filter(p=>p.k==='drawerfront').length===1,
    JSON.stringify(res.parts.filter(p=>p.k==='door'||p.k==='drawerfront').map(p=>({k:p.k,plannerFront:!!p.plannerFront}))));
}

/* ── the legitimate case must still work: plain open interior + the
   frame's own exterior front is the ONLY front, and it must still render ── */
{
  const cfg={columns:[{w:1,zones:[{type:'open',ratio:1,shelves:3,rail:true}]}],
    wardrobePlanner:{room:{w:mm(1100),d:mm(2500),h:mm(2400)},
      frames:[{id:'f1',wall:'back',w:mm(900),d:mm(600),h:mm(2300),front:'hinged',frontCount:1,handle:'bar',zones:null}],
      obstacles:[],frameColor:'#F4F2ED',frontColor:'#F4F2ED'}};
  cfg.wardrobePlanner.frames[0].zones=cfg.columns[0].zones;
  cfg.zones=cfg.columns[0].zones;
  const res=W.generate(cfg,fit);
  const doors=res.parts.filter(p=>p.k==='door');
  t.ok('a plain-interior frame still gets its own exterior front (exactly one door part)',
    doors.length===1&&doors[0].plannerFront===true, JSON.stringify(doors));
}

t.report();
